### ISSUE TITLE
Guardが動くけどエラーが出る問題

### ISSUE THREAD

**Issue by Komei22** [Komei22/rails-tutorial#3]
# Guardが動くけどエラーが出る問題

## 状況
Guardをインストールして起動できるが、テストの実行を行うとエラーが出る

```
[1] guard(main)>
18:29:33 - INFO - Run all
18:29:33 - INFO - Running: all tests
/usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler/setup (LoadError)
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/komei.nomura/dev/sample_app/config/boot.rb:3:in `<top (required)>'
	from bin/rails:3:in `require_relative'
	from bin/rails:3:in `<main>'
```

## エラーの要約
bundler/setupというファイルが見つけられなくてエラーとなっている

## 原因
'bundle install'を行うときに、'--path /vendor/bundleのオプションをつけ、gemファイルのインストール場所を'/app root/vendor/bundle'に設定した
これを行うと、グローバルな環境にgemをインストールするのではなく、appのローカルにインストールするようになる。
この影響でグローバルな環境の`bundler/setup/`がない状況になっていた

## 解消方法
プロジェクトルート/.bundle/configというファイルをいじります。
ファイル内に
BUNDLE_DISABLE_SHARED_GEMS: "true"
という記述があると思います。
この値が"true"となっていた場合、システムにインストールしたgemは使わないという設定になります。
この場合、システムのgemに依存しなくなるため、アプリケーションの独立性が保たれます。
しかし、今回の場合はgurdの部分でシステムのgemを使いたいので"false"にすることで解消された。

**Comment by Asuforce** [comment]
僕の環境だと、 `--path` オプション付けても正常に guard が走りました。

bundler のバージョンとかかなとエスパー

```
~/w/g/A/rails_tutorial_2017 ❯❯❯ rails -v                                                                                                                                                                                            master ✱ ◼
Rails 5.0.3
~/w/g/A/rails_tutorial_2017 ❯❯❯ ruby -v                                                                                                                                                                                             master ✱ ◼
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
~/w/g/A/rails_tutorial_2017 ❯❯❯ bundler version                                                                                                                                                                                     master ✱ ◼
Bundler version 1.15.1
```
